source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '5.1.7'
# Use postgresql as the database for Active Record
gem 'pg', '1.1.4'
# Use Puma as the app server
gem 'puma', '3.12.1'
# Use SCSS for stylesheets
gem 'sass-rails', '5.0.7'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '4.1.20'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '4.2.2'
gem 'coffee-script', '2.4.1'
gem 'coffee-script-source', '1.8.0'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '5.2.0'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '2.8.0'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '3.1.12'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'C' anywhere in the code to stop execution and get a debugger console
  gem 'byebug','11.0.1'
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '3.18.0'
  gem 'selenium-webdriver','3.142.0'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console', '3.7.0'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data','1.2019.1'

# 環境変数設定
gem 'dotenv-rails','2.7.2'
gem 'bcrypt-ruby', '3.0.1'

# データ投入
gem 'csv', '3.1.1'
# 定数管理
gem 'settingslogic'

gem 'webpacker', github: 'rails/webpacker'

# ユーザー管理
gem 'devise','4.6.2'
gem 'cancancan','3.0.1'
# 管理者画面
#gem 'rails_admin','1.4.2'

# クライアント（レイアウト）
gem 'bootstrap-sass','3.4.1'
gem 'jquery-rails','4.3.3'
gem 'font-awesome-sass','4.7.0'

source 'https://rails-assets.org/' do 
  gem 'rails-assets-adminlte', '2.3.11'
end
